#motion params

control_rate : 20

#navigation
takeoff_height : 5.0
return_height : 5.0
nav_xy_pos_pgain : 0.9
nav_z_pos_pgain : 0.8
nav_yaw_pgain : 1.2
nav_xy_vel_thresh : 0.5
nav_z_vel_thresh : 1.0
nav_yaw_vel_thresh : 0.6
nav_pos_convergence_thresh : 0.1
nav_yaw_convergence_thresh : 0.15
nav_vel_convergence_thresh : 1.0
takeoff_forward_offset : 0.0 # positive value
deep_return_dist : -2.0 # negative value
turn_radius_offset : -1.0 # negative value

#circle motion
circle_radius : 0.9
circle_y_vel : 0.3
circle_motion_height_step : 0.5

#obstacle avoidance
cluster_num_min : 10
safe_zone_radius : 1.0
drone_obstacle_ignore_maximum_radius : 0.90
drone_safety_minimum_radius : 0.85
avoid_vel : 0.5